import { Recipe } from "@shared/schema";

// 20 starter recipes for the DigiCook app
export const starterRecipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Spaghetti Carbonara",
    description: "A creamy Italian pasta dish with eggs, cheese, and pancetta",
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=600&fit=crop",
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Italian",
    dietary: [],
    ingredients: [
      { name: "Spaghetti", amount: "400", unit: "g" },
      { name: "Pancetta", amount: "200", unit: "g" },
      { name: "Eggs", amount: "4", unit: "whole" },
      { name: "Parmesan cheese", amount: "100", unit: "g" },
      { name: "Black pepper", amount: "to taste" },
    ],
    steps: [
      "Cook spaghetti in salted boiling water until al dente",
      "Meanwhile, fry pancetta until crispy",
      "Beat eggs with grated parmesan and black pepper",
      "Drain pasta, reserving 1 cup of pasta water",
      "Mix hot pasta with pancetta, then remove from heat",
      "Add egg mixture, tossing quickly. Add pasta water if needed",
      "Serve immediately with extra parmesan"
    ],
    nutrition: { calories: 520, protein: 28, carbs: 62, fat: 18, fiber: 3 },
    isPersonal: false,
  },
  {
    id: "2",
    title: "Grilled Chicken Salad",
    description: "Fresh and healthy salad with grilled chicken breast and mixed greens",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop",
    cookTime: 20,
    servings: 2,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["gluten-free"],
    ingredients: [
      { name: "Chicken breast", amount: "2", unit: "pieces" },
      { name: "Mixed salad greens", amount: "4", unit: "cups" },
      { name: "Cherry tomatoes", amount: "1", unit: "cup" },
      { name: "Cucumber", amount: "1", unit: "whole" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Season chicken breasts with salt and pepper",
      "Grill chicken for 6-7 minutes each side until cooked through",
      "Let chicken rest for 5 minutes, then slice",
      "Toss greens, tomatoes, and cucumber in a bowl",
      "Whisk olive oil and lemon juice for dressing",
      "Top salad with sliced chicken and drizzle with dressing"
    ],
    nutrition: { calories: 320, protein: 38, carbs: 12, fat: 14, fiber: 4 },
    isPersonal: false,
  },
  {
    id: "3",
    title: "Vegetable Stir Fry",
    description: "Colorful and nutritious vegetable stir fry with soy sauce",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=600&fit=crop",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Asian",
    dietary: ["vegetarian", "vegan"],
    ingredients: [
      { name: "Bell peppers", amount: "2", unit: "whole" },
      { name: "Broccoli", amount: "2", unit: "cups" },
      { name: "Carrots", amount: "2", unit: "whole" },
      { name: "Soy sauce", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Ginger", amount: "1", unit: "tbsp" },
      { name: "Sesame oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cut all vegetables into bite-sized pieces",
      "Heat sesame oil in a large wok over high heat",
      "Add minced garlic and ginger, stir for 30 seconds",
      "Add carrots and broccoli, stir-fry for 3 minutes",
      "Add bell peppers, cook for 2 more minutes",
      "Add soy sauce, toss well and serve hot"
    ],
    nutrition: { calories: 180, protein: 6, carbs: 24, fat: 8, fiber: 6 },
    isPersonal: false,
  },
  {
    id: "4",
    title: "Chocolate Chip Cookies",
    description: "Soft and chewy homemade chocolate chip cookies",
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&h=600&fit=crop",
    cookTime: 30,
    servings: 24,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["vegetarian"],
    ingredients: [
      { name: "Butter", amount: "1", unit: "cup" },
      { name: "Sugar", amount: "1", unit: "cup" },
      { name: "Brown sugar", amount: "1", unit: "cup" },
      { name: "Eggs", amount: "2", unit: "whole" },
      { name: "Flour", amount: "3", unit: "cups" },
      { name: "Chocolate chips", amount: "2", unit: "cups" },
      { name: "Vanilla extract", amount: "2", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 375°F (190°C)",
      "Cream together butter and both sugars",
      "Beat in eggs and vanilla",
      "Mix in flour and baking soda",
      "Fold in chocolate chips",
      "Drop spoonfuls onto baking sheet",
      "Bake for 10-12 minutes until golden"
    ],
    nutrition: { calories: 210, protein: 3, carbs: 28, fat: 11, sugar: 18 },
    isPersonal: false,
  },
  {
    id: "5",
    title: "Margherita Pizza",
    description: "Classic Italian pizza with tomato, mozzarella, and fresh basil",
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop",
    cookTime: 45,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Italian",
    dietary: ["vegetarian"],
    ingredients: [
      { name: "Pizza dough", amount: "500", unit: "g" },
      { name: "Tomato sauce", amount: "1", unit: "cup" },
      { name: "Mozzarella", amount: "250", unit: "g" },
      { name: "Fresh basil", amount: "1", unit: "bunch" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Preheat oven to 475°F (245°C)",
      "Roll out pizza dough into a circle",
      "Spread tomato sauce evenly over dough",
      "Tear mozzarella and distribute on top",
      "Drizzle with olive oil",
      "Bake for 12-15 minutes until crust is golden",
      "Top with fresh basil leaves before serving"
    ],
    nutrition: { calories: 380, protein: 16, carbs: 48, fat: 14 },
    isPersonal: false,
  },
  {
    id: "6",
    title: "Beef Tacos",
    description: "Spicy ground beef tacos with fresh toppings",
    imageUrl: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&h=600&fit=crop",
    cookTime: 20,
    servings: 6,
    difficulty: "Easy",
    cuisine: "Mexican",
    dietary: [],
    ingredients: [
      { name: "Ground beef", amount: "500", unit: "g" },
      { name: "Taco seasoning", amount: "2", unit: "tbsp" },
      { name: "Taco shells", amount: "12", unit: "pieces" },
      { name: "Lettuce", amount: "2", unit: "cups" },
      { name: "Tomatoes", amount: "2", unit: "whole" },
      { name: "Cheese", amount: "1", unit: "cup" },
      { name: "Sour cream", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Brown ground beef in a large skillet",
      "Add taco seasoning and 1/4 cup water",
      "Simmer for 5 minutes until thickened",
      "Warm taco shells in oven",
      "Chop lettuce and dice tomatoes",
      "Fill shells with beef and toppings"
    ],
    nutrition: { calories: 340, protein: 22, carbs: 28, fat: 16 },
    isPersonal: false,
  },
  {
    id: "7",
    title: "Greek Salad",
    description: "Traditional Greek salad with feta cheese and olives",
    imageUrl: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=600&fit=crop",
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Greek",
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      { name: "Cucumbers", amount: "2", unit: "whole" },
      { name: "Tomatoes", amount: "4", unit: "whole" },
      { name: "Red onion", amount: "1", unit: "whole" },
      { name: "Feta cheese", amount: "200", unit: "g" },
      { name: "Kalamata olives", amount: "1", unit: "cup" },
      { name: "Olive oil", amount: "1/4", unit: "cup" },
      { name: "Oregano", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Chop cucumbers and tomatoes into chunks",
      "Slice red onion thinly",
      "Combine vegetables in a large bowl",
      "Add olives and crumbled feta",
      "Drizzle with olive oil",
      "Sprinkle with oregano and toss gently"
    ],
    nutrition: { calories: 220, protein: 8, carbs: 14, fat: 16, fiber: 4 },
    isPersonal: false,
  },
  {
    id: "8",
    title: "Pancakes",
    description: "Fluffy American-style pancakes perfect for breakfast",
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop",
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["vegetarian"],
    ingredients: [
      { name: "Flour", amount: "2", unit: "cups" },
      { name: "Milk", amount: "2", unit: "cups" },
      { name: "Eggs", amount: "2", unit: "whole" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Baking powder", amount: "2", unit: "tsp" },
      { name: "Butter", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Mix flour, sugar, and baking powder in a bowl",
      "Whisk eggs and milk together",
      "Combine wet and dry ingredients",
      "Melt butter and add to batter",
      "Heat a griddle over medium heat",
      "Pour batter and cook until bubbles form",
      "Flip and cook other side until golden"
    ],
    nutrition: { calories: 310, protein: 10, carbs: 48, fat: 9 },
    isPersonal: false,
  },
  {
    id: "9",
    title: "Chicken Curry",
    description: "Aromatic Indian-style chicken curry with spices",
    imageUrl: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&h=600&fit=crop",
    cookTime: 45,
    servings: 6,
    difficulty: "Medium",
    cuisine: "Indian",
    dietary: ["gluten-free"],
    ingredients: [
      { name: "Chicken thighs", amount: "800", unit: "g" },
      { name: "Onions", amount: "2", unit: "whole" },
      { name: "Tomatoes", amount: "3", unit: "whole" },
      { name: "Curry powder", amount: "3", unit: "tbsp" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Ginger", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cut chicken into bite-sized pieces",
      "Sauté onions, garlic, and ginger until soft",
      "Add curry powder and cook for 1 minute",
      "Add chicken and brown on all sides",
      "Add chopped tomatoes and coconut milk",
      "Simmer for 30 minutes until chicken is tender",
      "Serve with rice or naan bread"
    ],
    nutrition: { calories: 420, protein: 32, carbs: 18, fat: 26 },
    isPersonal: false,
  },
  {
    id: "10",
    title: "Caesar Salad",
    description: "Classic Caesar salad with homemade dressing and croutons",
    imageUrl: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "American",
    dietary: [],
    ingredients: [
      { name: "Romaine lettuce", amount: "2", unit: "heads" },
      { name: "Parmesan cheese", amount: "1", unit: "cup" },
      { name: "Croutons", amount: "2", unit: "cups" },
      { name: "Mayonnaise", amount: "1/2", unit: "cup" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Anchovy paste", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Chop romaine lettuce into bite-sized pieces",
      "Mix mayonnaise, lemon juice, minced garlic, and anchovy paste",
      "Toss lettuce with dressing",
      "Add grated parmesan and croutons",
      "Toss again and serve immediately"
    ],
    nutrition: { calories: 280, protein: 12, carbs: 18, fat: 18 },
    isPersonal: false,
  },
  {
    id: "11",
    title: "Salmon Teriyaki",
    description: "Glazed salmon with sweet and savory teriyaki sauce",
    imageUrl: "https://images.unsplash.com/photo-1580959375944-78a59c2e3ccd?w=800&h=600&fit=crop",
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Japanese",
    dietary: ["gluten-free"],
    ingredients: [
      { name: "Salmon fillets", amount: "4", unit: "pieces" },
      { name: "Soy sauce", amount: "1/4", unit: "cup" },
      { name: "Honey", amount: "2", unit: "tbsp" },
      { name: "Ginger", amount: "1", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Rice vinegar", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Mix soy sauce, honey, ginger, garlic, and vinegar",
      "Marinate salmon for 15 minutes",
      "Heat a pan over medium-high heat",
      "Cook salmon skin-side down for 5 minutes",
      "Flip and cook for 4 more minutes",
      "Brush with remaining marinade and serve"
    ],
    nutrition: { calories: 340, protein: 34, carbs: 12, fat: 18 },
    isPersonal: false,
  },
  {
    id: "12",
    title: "Vegetable Soup",
    description: "Hearty and comforting vegetable soup with herbs",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop",
    cookTime: 40,
    servings: 6,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["vegetarian", "vegan", "gluten-free"],
    ingredients: [
      { name: "Carrots", amount: "3", unit: "whole" },
      { name: "Celery", amount: "3", unit: "stalks" },
      { name: "Potatoes", amount: "2", unit: "whole" },
      { name: "Onion", amount: "1", unit: "whole" },
      { name: "Vegetable broth", amount: "6", unit: "cups" },
      { name: "Tomatoes", amount: "2", unit: "whole" },
      { name: "Herbs", amount: "to taste" },
    ],
    steps: [
      "Chop all vegetables into small pieces",
      "Sauté onion in a large pot until soft",
      "Add carrots, celery, and potatoes",
      "Pour in vegetable broth",
      "Add chopped tomatoes and herbs",
      "Simmer for 30 minutes until vegetables are tender"
    ],
    nutrition: { calories: 120, protein: 3, carbs: 26, fat: 1, fiber: 5 },
    isPersonal: false,
  },
  {
    id: "13",
    title: "Pad Thai",
    description: "Classic Thai noodle dish with peanuts and lime",
    imageUrl: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop",
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    cuisine: "Thai",
    dietary: [],
    ingredients: [
      { name: "Rice noodles", amount: "300", unit: "g" },
      { name: "Shrimp", amount: "300", unit: "g" },
      { name: "Eggs", amount: "2", unit: "whole" },
      { name: "Bean sprouts", amount: "2", unit: "cups" },
      { name: "Peanuts", amount: "1/2", unit: "cup" },
      { name: "Tamarind paste", amount: "2", unit: "tbsp" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Soak rice noodles in warm water for 20 minutes",
      "Heat oil in a wok over high heat",
      "Stir-fry shrimp until pink",
      "Push aside and scramble eggs",
      "Add drained noodles and sauce",
      "Toss with bean sprouts and peanuts",
      "Serve with lime wedges"
    ],
    nutrition: { calories: 450, protein: 28, carbs: 58, fat: 12 },
    isPersonal: false,
  },
  {
    id: "14",
    title: "Banana Bread",
    description: "Moist and delicious banana bread perfect for breakfast or snack",
    imageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&h=600&fit=crop",
    cookTime: 65,
    servings: 10,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["vegetarian"],
    ingredients: [
      { name: "Ripe bananas", amount: "3", unit: "whole" },
      { name: "Flour", amount: "2", unit: "cups" },
      { name: "Sugar", amount: "3/4", unit: "cup" },
      { name: "Butter", amount: "1/2", unit: "cup" },
      { name: "Eggs", amount: "2", unit: "whole" },
      { name: "Baking soda", amount: "1", unit: "tsp" },
      { name: "Vanilla", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 350°F (175°C)",
      "Mash bananas in a bowl",
      "Mix in melted butter",
      "Stir in sugar, eggs, and vanilla",
      "Mix in flour and baking soda",
      "Pour into greased loaf pan",
      "Bake for 60 minutes until golden"
    ],
    nutrition: { calories: 240, protein: 4, carbs: 42, fat: 8, sugar: 22 },
    isPersonal: false,
  },
  {
    id: "15",
    title: "Caprese Salad",
    description: "Simple Italian salad with tomatoes, mozzarella, and basil",
    imageUrl: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800&h=600&fit=crop",
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Italian",
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      { name: "Tomatoes", amount: "4", unit: "whole" },
      { name: "Fresh mozzarella", amount: "250", unit: "g" },
      { name: "Fresh basil", amount: "1", unit: "bunch" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Balsamic vinegar", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Slice tomatoes and mozzarella into rounds",
      "Arrange alternating slices on a platter",
      "Tuck basil leaves between slices",
      "Drizzle with olive oil and balsamic vinegar",
      "Season with salt and pepper"
    ],
    nutrition: { calories: 220, protein: 12, carbs: 8, fat: 16 },
    isPersonal: false,
  },
  {
    id: "16",
    title: "French Toast",
    description: "Classic French toast with cinnamon and vanilla",
    imageUrl: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&h=600&fit=crop",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    cuisine: "French",
    dietary: ["vegetarian"],
    ingredients: [
      { name: "Bread", amount: "8", unit: "slices" },
      { name: "Eggs", amount: "4", unit: "whole" },
      { name: "Milk", amount: "1/2", unit: "cup" },
      { name: "Cinnamon", amount: "1", unit: "tsp" },
      { name: "Vanilla", amount: "1", unit: "tsp" },
      { name: "Butter", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Whisk eggs, milk, cinnamon, and vanilla",
      "Heat butter in a large skillet",
      "Dip bread slices in egg mixture",
      "Cook each side for 2-3 minutes until golden",
      "Serve with maple syrup and fresh fruit"
    ],
    nutrition: { calories: 280, protein: 12, carbs: 36, fat: 10 },
    isPersonal: false,
  },
  {
    id: "17",
    title: "Quinoa Bowl",
    description: "Healthy quinoa bowl with roasted vegetables and tahini",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop",
    cookTime: 35,
    servings: 4,
    difficulty: "Easy",
    cuisine: "Mediterranean",
    dietary: ["vegetarian", "vegan", "gluten-free"],
    ingredients: [
      { name: "Quinoa", amount: "1", unit: "cup" },
      { name: "Sweet potato", amount: "1", unit: "whole" },
      { name: "Chickpeas", amount: "1", unit: "can" },
      { name: "Kale", amount: "2", unit: "cups" },
      { name: "Tahini", amount: "1/4", unit: "cup" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cook quinoa according to package directions",
      "Dice sweet potato and roast at 400°F for 25 minutes",
      "Rinse and roast chickpeas with spices",
      "Massage kale with a bit of olive oil",
      "Mix tahini with lemon juice for dressing",
      "Assemble bowls with quinoa, vegetables, and dressing"
    ],
    nutrition: { calories: 380, protein: 14, carbs: 58, fat: 12, fiber: 12 },
    isPersonal: false,
  },
  {
    id: "18",
    title: "Mushroom Risotto",
    description: "Creamy Italian rice dish with mushrooms and parmesan",
    imageUrl: "https://images.unsplash.com/photo-1476124369491-c4cc9249ee e6?w=800&h=600&fit=crop",
    cookTime: 40,
    servings: 4,
    difficulty: "Hard",
    cuisine: "Italian",
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      { name: "Arborio rice", amount: "2", unit: "cups" },
      { name: "Mushrooms", amount: "400", unit: "g" },
      { name: "Vegetable broth", amount: "6", unit: "cups" },
      { name: "White wine", amount: "1/2", unit: "cup" },
      { name: "Parmesan", amount: "1", unit: "cup" },
      { name: "Butter", amount: "3", unit: "tbsp" },
      { name: "Onion", amount: "1", unit: "whole" },
    ],
    steps: [
      "Heat broth in a separate pot and keep warm",
      "Sauté diced onion and sliced mushrooms in butter",
      "Add rice and toast for 2 minutes",
      "Add wine and stir until absorbed",
      "Add broth one ladle at a time, stirring constantly",
      "Continue until rice is creamy, about 25 minutes",
      "Stir in parmesan and serve immediately"
    ],
    nutrition: { calories: 420, protein: 14, carbs: 64, fat: 12 },
    isPersonal: false,
  },
  {
    id: "19",
    title: "BBQ Ribs",
    description: "Tender and smoky barbecue ribs with homemade sauce",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop",
    cookTime: 180,
    servings: 6,
    difficulty: "Hard",
    cuisine: "American",
    dietary: [],
    ingredients: [
      { name: "Pork ribs", amount: "2", unit: "racks" },
      { name: "BBQ rub", amount: "1/4", unit: "cup" },
      { name: "BBQ sauce", amount: "2", unit: "cups" },
      { name: "Apple cider vinegar", amount: "1/4", unit: "cup" },
      { name: "Brown sugar", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Remove membrane from back of ribs",
      "Apply BBQ rub generously on both sides",
      "Wrap in foil and refrigerate for 2 hours",
      "Preheat oven to 275°F (135°C)",
      "Bake wrapped ribs for 2.5 hours",
      "Unwrap, brush with sauce, and broil for 5 minutes",
      "Let rest before cutting between bones"
    ],
    nutrition: { calories: 620, protein: 42, carbs: 28, fat: 38 },
    isPersonal: false,
  },
  {
    id: "20",
    title: "Smoothie Bowl",
    description: "Refreshing and nutritious smoothie bowl with fresh fruit toppings",
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=600&fit=crop",
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    cuisine: "American",
    dietary: ["vegetarian", "vegan", "gluten-free"],
    ingredients: [
      { name: "Frozen berries", amount: "2", unit: "cups" },
      { name: "Banana", amount: "2", unit: "whole" },
      { name: "Almond milk", amount: "1", unit: "cup" },
      { name: "Granola", amount: "1/2", unit: "cup" },
      { name: "Fresh fruit", amount: "1", unit: "cup" },
      { name: "Chia seeds", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Blend frozen berries, banana, and almond milk until smooth",
      "Pour into bowls",
      "Top with granola, fresh fruit, and chia seeds",
      "Add any other desired toppings",
      "Serve immediately"
    ],
    nutrition: { calories: 280, protein: 6, carbs: 52, fat: 8, fiber: 10 },
    isPersonal: false,
  },
];
