import { initializeApp } from "firebase/app";
import { getFirestore, collection, doc, setDoc } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "AIzaSyAUwQhIBpyvubYME6e0oydxPn_u5DwJUDg",
  authDomain: "digicook-2ecbe.firebaseapp.com",
  projectId: "digicook-2ecbe",
  storageBucket: "digicook-2ecbe.firebasestorage.app",
  messagingSenderId: "21145060975",
  appId: "1:21145060975:web:d4ada2a7adc5235c026f9a",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// ✅ All working Unsplash URLs
const publicRecipes = [
  {
    id: "greek-salad",
    title: "Greek Salad",
    description: "Refreshing salad with tomatoes, cucumber, olives, and feta cheese.",
    imageUrl: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
    ingredients: [
      { name: "Tomatoes", amount: "2" },
      { name: "Cucumber", amount: "1" },
      { name: "Feta cheese", amount: "150", unit: "g" },
      { name: "Olives", amount: "10" },
    ],
    steps: [
      "Chop vegetables.",
      "Mix all ingredients in a bowl.",
      "Add olive oil and oregano to taste.",
    ],
    cookTime: "10 min",
  },
  {
    id: "spaghetti-carbonara",
    title: "Spaghetti Carbonara",
    description: "Classic Italian pasta with eggs, cheese, pancetta, and black pepper.",
    imageUrl: "https://images.unsplash.com/photo-1589308078054-83211a1c1a23",
    ingredients: [
      { name: "Spaghetti", amount: "200", unit: "g" },
      { name: "Eggs", amount: "2" },
      { name: "Pancetta", amount: "100", unit: "g" },
      { name: "Parmesan cheese", amount: "50", unit: "g" },
    ],
    steps: [
      "Boil pasta in salted water.",
      "Cook pancetta until crispy.",
      "Mix eggs with grated cheese.",
      "Combine all together off heat and season with pepper.",
    ],
    cookTime: "25 min",
  },
  {
    id: "chicken-alfredo",
    title: "Chicken Alfredo Pasta",
    description: "Creamy fettuccine Alfredo with grilled chicken and parmesan.",
    imageUrl:
      "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1470",
    ingredients: [
      { name: "Fettuccine", amount: "250", unit: "g" },
      { name: "Chicken breast", amount: "1" },
      { name: "Heavy cream", amount: "1", unit: "cup" },
      { name: "Parmesan cheese", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Cook pasta until al dente.",
      "Grill chicken and slice.",
      "Simmer cream and cheese until thick.",
      "Combine pasta with sauce and chicken.",
    ],
    cookTime: "30 min",
  },
  {
    id: "caprese-sandwich",
    title: "Caprese Sandwich",
    description: "Mozzarella, tomatoes, and basil with balsamic glaze on ciabatta.",
    imageUrl: "https://images.unsplash.com/photo-1590080875832-01c2b86af08f",
    ingredients: [
      { name: "Ciabatta bread", amount: "1" },
      { name: "Tomatoes", amount: "2" },
      { name: "Mozzarella cheese", amount: "100", unit: "g" },
      { name: "Basil leaves", amount: "5" },
    ],
    steps: [
      "Slice bread and toast lightly.",
      "Layer mozzarella, tomato, and basil.",
      "Drizzle with olive oil and balsamic glaze.",
    ],
    cookTime: "10 min",
  },
  {
    id: "beef-tacos",
    title: "Beef Tacos",
    description: "Crispy tacos with seasoned ground beef, lettuce, and cheese.",
    imageUrl: "https://images.unsplash.com/photo-1617196035056-c5e052d3f36c",
    ingredients: [
      { name: "Ground beef", amount: "300", unit: "g" },
      { name: "Taco shells", amount: "6" },
      { name: "Cheddar cheese", amount: "100", unit: "g" },
      { name: "Lettuce", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Cook beef with taco seasoning.",
      "Fill taco shells with beef, lettuce, and cheese.",
      "Serve immediately.",
    ],
    cookTime: "20 min",
  },
  {
    id: "chicken-curry",
    title: "Chicken Curry",
    description: "A mild, flavorful curry made with coconut milk and tender chicken.",
    imageUrl: "https://images.unsplash.com/photo-1627308595187-9b6f68d1c7da",
    ingredients: [
      { name: "Chicken breast", amount: "2" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Curry powder", amount: "2", unit: "tbsp" },
      { name: "Onion", amount: "1" },
    ],
    steps: [
      "Sauté onions until golden.",
      "Add chicken and brown lightly.",
      "Stir in curry powder and coconut milk.",
      "Simmer until sauce thickens.",
    ],
    cookTime: "40 min",
  },
  {
    id: "pancakes",
    title: "Fluffy Pancakes",
    description: "Soft, fluffy pancakes perfect for breakfast or brunch.",
    imageUrl:
      "https://images.unsplash.com/photo-1588765907995-47867ce30312?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1374",
    ingredients: [
      { name: "Flour", amount: "1.5", unit: "cups" },
      { name: "Milk", amount: "1.25", unit: "cups" },
      { name: "Egg", amount: "1" },
      { name: "Baking powder", amount: "3.5", unit: "tsp" },
    ],
    steps: [
      "Mix dry ingredients.",
      "Whisk in milk and egg until smooth.",
      "Cook batter on a lightly greased pan.",
    ],
    cookTime: "15 min",
  },
  {
    id: "bruschetta",
    title: "Tomato Bruschetta",
    description: "Toasted bread topped with garlic, diced tomatoes, and basil.",
    imageUrl: "https://images.unsplash.com/photo-1565958011702-44e2111c0f4b",
    ingredients: [
      { name: "Baguette", amount: "1/2" },
      { name: "Tomatoes", amount: "2" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Basil leaves", amount: "5" },
    ],
    steps: [
      "Toast bread slices.",
      "Rub garlic on top and spoon tomato mixture over them.",
    ],
    cookTime: "10 min",
  },
  {
    id: "caesar-salad",
    title: "Caesar Salad",
    description: "Crisp romaine lettuce with creamy dressing and crunchy croutons.",
    imageUrl: "https://images.unsplash.com/photo-1606787366850-de6330128bfc",
    ingredients: [
      { name: "Romaine lettuce", amount: "1", unit: "head" },
      { name: "Croutons", amount: "1", unit: "cup" },
      { name: "Parmesan cheese", amount: "1/4", unit: "cup" },
      { name: "Caesar dressing", amount: "3", unit: "tbsp" },
    ],
    steps: [
      "Toss all ingredients together in a large bowl.",
      "Mix ingredients in the bowl until well coated with dressing.",
      "Serve or store in fridge.",
    ],
    cookTime: "5 min",
  },
  {
    id: "french-toast",
    title: "French Toast",
    description: "Classic breakfast of bread soaked in egg and milk, then fried.",
    imageUrl: "https://images.unsplash.com/photo-1588167106111-1bf62a3d5d15",
    ingredients: [
      { name: "Bread slices", amount: "4" },
      { name: "Eggs", amount: "2" },
      { name: "Milk", amount: "1/2", unit: "cup" },
      { name: "Cinnamon", amount: "1/2", unit: "tsp" },
    ],
    steps: [
      "Whisk eggs, milk, and cinnamon.",
      "Dip bread in mixture and fry on both sides until golden.",
    ],
    cookTime: "15 min",
  },
  {
    id: "margherita-pizza",
    title: "Margherita Pizza",
    description: "Classic pizza topped with tomato sauce, mozzarella, and fresh basil.",
    imageUrl: "https://images.unsplash.com/photo-1548369937-47519962c11a",
    ingredients: [
      { name: "Pizza dough", amount: "1" },
      { name: "Tomato sauce", amount: "1/2", unit: "cup" },
      { name: "Mozzarella cheese", amount: "150", unit: "g" },
      { name: "Fresh basil leaves", amount: "6" },
    ],
    steps: [
      "Preheat oven to 475°F (245°C).",
      "Spread tomato sauce over rolled-out dough.",
      "Top with mozzarella and basil.",
      "Bake until crust is golden and cheese is bubbly.",
    ],
    cookTime: "15 min",
  },
  {
    id: "veggie-burger",
    title: "Veggie Burger",
    description: "Hearty vegetarian burger patty served on a toasted bun.",
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    ingredients: [
      { name: "Veggie patty", amount: "1" },
      { name: "Burger bun", amount: "1" },
      { name: "Lettuce", amount: "2", unit: "leaves" },
      { name: "Tomato slices", amount: "2" },
    ],
    steps: [
      "Cook veggie patty in a pan or grill until heated through.",
      "Toast the bun lightly.",
      "Assemble burger with patty, lettuce, and tomato.",
    ],
    cookTime: "15 min",
  },
  {
    id: "lentil-soup",
    title: "Lentil Soup",
    description: "Comforting soup made with lentils, carrots, and celery.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088",
    ingredients: [
      { name: "Dried lentils", amount: "1", unit: "cup" },
      { name: "Carrots", amount: "2" },
      { name: "Celery stalks", amount: "2" },
      { name: "Vegetable broth", amount: "4", unit: "cups" },
    ],
    steps: [
      "Sauté chopped carrots and celery until softened.",
      "Add lentils and broth.",
      "Simmer until lentils are tender.",
    ],
    cookTime: "45 min",
  },
  {
    id: "bbq-chicken-pizza",
    title: "BBQ Chicken Pizza",
    description: "Pizza topped with barbecue sauce, grilled chicken, and red onions.",
    imageUrl: "https://images.unsplash.com/photo-1548369937-3a8e27c1c07f",
    ingredients: [
      { name: "Pizza dough", amount: "1" },
      { name: "BBQ sauce", amount: "1/2", unit: "cup" },
      { name: "Cooked chicken", amount: "150", unit: "g" },
      { name: "Red onion", amount: "1/2" },
    ],
    steps: [
      "Preheat oven to 475°F (245°C).",
      "Spread BBQ sauce over dough.",
      "Top with chicken and sliced red onion.",
      "Bake until cheese is melted and crust is crisp.",
    ],
    cookTime: "18 min",
  },
  {
    id: "shrimp-scampi",
    title: "Shrimp Scampi",
    description: "Garlicky shrimp served over pasta with lemon and parsley.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Shrimp", amount: "250", unit: "g" },
      { name: "Spaghetti", amount: "200", unit: "g" },
      { name: "Garlic cloves", amount: "3" },
      { name: "Butter", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cook pasta until al dente.",
      "Sauté garlic in butter, then add shrimp.",
      "Cook until shrimp are pink.",
      "Toss shrimp and sauce with pasta.",
    ],
    cookTime: "20 min",
  },
  {
    id: "vegan-buddha-bowl",
    title: "Vegan Buddha Bowl",
    description: "Colorful bowl with grains, roasted veggies, and chickpeas.",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    ingredients: [
      { name: "Cooked quinoa", amount: "1", unit: "cup" },
      { name: "Chickpeas", amount: "1", unit: "cup" },
      { name: "Sweet potato", amount: "1" },
      { name: "Spinach", amount: "1", unit: "cup" },
    ],
    steps: [
      "Roast cubed sweet potato until tender.",
      "Arrange quinoa in a bowl.",
      "Top with sweet potato, chickpeas, and spinach.",
      "Drizzle with tahini or dressing of choice.",
    ],
    cookTime: "35 min",
  },
  {
    id: "beef-stroganoff",
    title: "Beef Stroganoff",
    description: "Creamy beef and mushroom sauce served over egg noodles.",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    ingredients: [
      { name: "Beef strips", amount: "300", unit: "g" },
      { name: "Mushrooms", amount: "1", unit: "cup" },
      { name: "Onion", amount: "1/2" },
      { name: "Sour cream", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Brown beef in a pan, then remove.",
      "Sauté onions and mushrooms.",
      "Return beef and stir in sour cream.",
      "Serve over cooked egg noodles.",
    ],
    cookTime: "35 min",
  },
  {
    id: "chili-con-carne",
    title: "Chili con Carne",
    description: "Spicy stew of ground beef, beans, and tomatoes.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-9317f6c3c4cc",
    ingredients: [
      { name: "Ground beef", amount: "400", unit: "g" },
      { name: "Kidney beans", amount: "1", unit: "can" },
      { name: "Tomato sauce", amount: "1", unit: "cup" },
      { name: "Chili powder", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Brown ground beef.",
      "Add beans, tomato sauce, and chili powder.",
      "Simmer until thickened.",
    ],
    cookTime: "45 min",
  },
  {
    id: "butternut-squash-soup",
    title: "Butternut Squash Soup",
    description: "Smooth and creamy roasted butternut squash soup.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873cf53e7d1c",
    ingredients: [
      { name: "Butternut squash", amount: "1", unit: "medium" },
      { name: "Onion", amount: "1" },
      { name: "Vegetable broth", amount: "4", unit: "cups" },
      { name: "Cream", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Roast peeled and cubed squash until soft.",
      "Sauté onions, then add squash and broth.",
      "Simmer, then blend until smooth.",
      "Stir in cream and season.",
    ],
    cookTime: "50 min",
  },
  {
    id: "garlic-butter-steak",
    title: "Garlic Butter Steak",
    description: "Pan-seared steak basted with garlic and butter.",
    imageUrl: "https://images.unsplash.com/photo-1553163147-622ab57be1c7",
    ingredients: [
      { name: "Steak", amount: "1", unit: "lb" },
      { name: "Butter", amount: "3", unit: "tbsp" },
      { name: "Garlic cloves", amount: "3" },
      { name: "Rosemary sprig", amount: "1" },
    ],
    steps: [
      "Season steak with salt and pepper.",
      "Sear in a hot pan on both sides.",
      "Add butter, garlic, and rosemary and baste steak.",
      "Rest before slicing.",
    ],
    cookTime: "20 min",
  },
  {
    id: "fish-and-chips",
    title: "Fish and Chips",
    description: "Crispy battered fish served with fries.",
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
    ingredients: [
      { name: "White fish fillets", amount: "4" },
      { name: "Flour", amount: "1", unit: "cup" },
      { name: "Beer or sparkling water", amount: "1", unit: "cup" },
      { name: "Potatoes", amount: "3" },
    ],
    steps: [
      "Cut potatoes into fries and fry until golden.",
      "Prepare batter with flour and beer.",
      "Dip fish in batter and fry until crispy.",
      "Serve with fries and lemon wedges.",
    ],
    cookTime: "40 min",
  },
  {
    id: "vegetable-stir-fry",
    title: "Vegetable Stir-Fry",
    description: "Quick stir-fried vegetables with a savory sauce.",
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19",
    ingredients: [
      { name: "Broccoli florets", amount: "1", unit: "cup" },
      { name: "Bell pepper", amount: "1" },
      { name: "Carrot", amount: "1" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Heat oil in a wok.",
      "Add sliced vegetables and stir-fry.",
      "Add soy sauce and a splash of water.",
      "Cook until vegetables are crisp-tender.",
    ],
    cookTime: "15 min",
  },
  {
    id: "mushroom-risotto",
    title: "Mushroom Risotto",
    description: "Creamy risotto with sautéed mushrooms and parmesan.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873cf53e7d1c",
    ingredients: [
      { name: "Arborio rice", amount: "1", unit: "cup" },
      { name: "Mushrooms", amount: "1", unit: "cup" },
      { name: "Vegetable broth", amount: "4", unit: "cups" },
      { name: "Parmesan cheese", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Sauté mushrooms, then remove.",
      "Toast rice in the pan.",
      "Gradually add warm broth, stirring until absorbed.",
      "Stir in mushrooms and parmesan.",
    ],
    cookTime: "40 min",
  },
  {
    id: "grilled-salmon",
    title: "Grilled Salmon",
    description: "Simple grilled salmon fillets with lemon.",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    ingredients: [
      { name: "Salmon fillets", amount: "2" },
      { name: "Olive oil", amount: "1", unit: "tbsp" },
      { name: "Lemon", amount: "1" },
      { name: "Garlic clove", amount: "1" },
    ],
    steps: [
      "Brush salmon with oil and season.",
      "Grill until cooked through.",
      "Serve with lemon wedges and minced garlic.",
    ],
    cookTime: "15 min",
  },
  {
    id: "stuffed-bell-peppers",
    title: "Stuffed Bell Peppers",
    description: "Bell peppers filled with rice, beef, and tomatoes.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Bell peppers", amount: "4" },
      { name: "Ground beef", amount: "300", unit: "g" },
      { name: "Cooked rice", amount: "1", unit: "cup" },
      { name: "Tomato sauce", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Cut tops off peppers and remove seeds.",
      "Mix beef, rice, and tomato sauce.",
      "Stuff peppers and place in a baking dish.",
      "Bake until peppers are tender.",
    ],
    cookTime: "50 min",
  },
  {
    id: "chicken-fajitas",
    title: "Chicken Fajitas",
    description: "Sizzling chicken strips with peppers and onions.",
    imageUrl: "https://images.unsplash.com/photo-1608038509085-7bb9d5c0b93c",
    ingredients: [
      { name: "Chicken breast", amount: "2" },
      { name: "Bell peppers", amount: "2" },
      { name: "Onion", amount: "1" },
      { name: "Fajita seasoning", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Slice chicken and vegetables.",
      "Cook chicken with seasoning.",
      "Add vegetables and cook until tender.",
      "Serve with warm tortillas.",
    ],
    cookTime: "25 min",
  },
  {
    id: "pad-thai",
    title: "Pad Thai",
    description: "Thai stir-fried rice noodles with shrimp and peanuts.",
    imageUrl: "https://images.unsplash.com/photo-1589308078054-83211a1c1a23",
    ingredients: [
      { name: "Rice noodles", amount: "200", unit: "g" },
      { name: "Shrimp", amount: "200", unit: "g" },
      { name: "Bean sprouts", amount: "1", unit: "cup" },
      { name: "Peanuts", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Soak rice noodles until soft.",
      "Stir-fry shrimp, then add noodles.",
      "Add sauce and toss with bean sprouts.",
      "Top with chopped peanuts.",
    ],
    cookTime: "30 min",
  },
  {
    id: "ramen-bowl",
    title: "Ramen Bowl",
    description: "Comforting bowl of noodles in savory broth with toppings.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c",
    ingredients: [
      { name: "Ramen noodles", amount: "2", unit: "packs" },
      { name: "Chicken broth", amount: "4", unit: "cups" },
      { name: "Eggs", amount: "2" },
      { name: "Green onions", amount: "2" },
    ],
    steps: [
      "Heat broth in a pot.",
      "Cook noodles in broth.",
      "Top with soft-boiled eggs and sliced green onions.",
    ],
    cookTime: "20 min",
  },
  {
    id: "sushi-rolls",
    title: "Sushi Rolls",
    description: "Simple cucumber and avocado sushi rolls.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-eacef0df6022",
    ingredients: [
      { name: "Sushi rice", amount: "2", unit: "cups" },
      { name: "Nori sheets", amount: "4" },
      { name: "Cucumber", amount: "1" },
      { name: "Avocado", amount: "1" },
    ],
    steps: [
      "Spread rice over nori sheets.",
      "Place cucumber and avocado in a line.",
      "Roll tightly and slice.",
    ],
    cookTime: "35 min",
  },
  {
    id: "falafel-wrap",
    title: "Falafel Wrap",
    description: "Crispy falafel wrapped in pita with veggies and tahini.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Falafel balls", amount: "6" },
      { name: "Pita bread", amount: "2" },
      { name: "Lettuce", amount: "1", unit: "cup" },
      { name: "Tahini sauce", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Warm pita bread.",
      "Fill with falafel, lettuce, and other veggies.",
      "Drizzle with tahini sauce.",
    ],
    cookTime: "20 min",
  },
  {
    id: "shakshuka",
    title: "Shakshuka",
    description: "Eggs poached in a spicy tomato and pepper sauce.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088",
    ingredients: [
      { name: "Eggs", amount: "4" },
      { name: "Tomatoes", amount: "4" },
      { name: "Bell pepper", amount: "1" },
      { name: "Onion", amount: "1" },
    ],
    steps: [
      "Sauté onion and pepper.",
      "Add chopped tomatoes and simmer.",
      "Crack eggs into sauce and cook until set.",
    ],
    cookTime: "30 min",
  },
  {
    id: "hummus-platter",
    title: "Hummus Platter",
    description: "Creamy hummus served with veggies and pita.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Chickpeas", amount: "1", unit: "can" },
      { name: "Tahini", amount: "2", unit: "tbsp" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Garlic clove", amount: "1" },
    ],
    steps: [
      "Blend chickpeas, tahini, lemon juice, and garlic until smooth.",
      "Drizzle with olive oil.",
      "Serve with sliced vegetables and pita.",
    ],
    cookTime: "15 min",
  },
  {
    id: "quiche-lorraine",
    title: "Quiche Lorraine",
    description: "Savory tart with bacon, cheese, and custard filling.",
    imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    ingredients: [
      { name: "Pie crust", amount: "1" },
      { name: "Eggs", amount: "4" },
      { name: "Milk or cream", amount: "1", unit: "cup" },
      { name: "Bacon", amount: "100", unit: "g" },
    ],
    steps: [
      "Pre-bake pie crust.",
      "Cook bacon and scatter in crust.",
      "Whisk eggs and milk, pour over bacon.",
      "Bake until set.",
    ],
    cookTime: "45 min",
  },
  {
    id: "mac-and-cheese",
    title: "Mac and Cheese",
    description: "Creamy baked macaroni and cheese.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088",
    ingredients: [
      { name: "Macaroni", amount: "2", unit: "cups" },
      { name: "Cheddar cheese", amount: "2", unit: "cups" },
      { name: "Milk", amount: "2", unit: "cups" },
      { name: "Butter", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cook macaroni until al dente.",
      "Make cheese sauce with butter, milk, and cheese.",
      "Combine with macaroni and bake.",
    ],
    cookTime: "35 min",
  },
  {
    id: "baked-ziti",
    title: "Baked Ziti",
    description: "Pasta baked with tomato sauce and melted cheese.",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e",
    ingredients: [
      { name: "Ziti pasta", amount: "300", unit: "g" },
      { name: "Tomato sauce", amount: "2", unit: "cups" },
      { name: "Mozzarella cheese", amount: "1.5", unit: "cups" },
      { name: "Ricotta cheese", amount: "1", unit: "cup" },
    ],
    steps: [
      "Cook pasta and drain.",
      "Mix with sauce and ricotta.",
      "Top with mozzarella and bake.",
    ],
    cookTime: "40 min",
  },
  {
    id: "chicken-parmesan",
    title: "Chicken Parmesan",
    description: "Breaded chicken cutlets baked with marinara and cheese.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Chicken breasts", amount: "2" },
      { name: "Breadcrumbs", amount: "1", unit: "cup" },
      { name: "Tomato sauce", amount: "1", unit: "cup" },
      { name: "Mozzarella cheese", amount: "1", unit: "cup" },
    ],
    steps: [
      "Bread and fry chicken cutlets.",
      "Place in baking dish with sauce and cheese.",
      "Bake until cheese is melted.",
    ],
    cookTime: "35 min",
  },
  {
    id: "pesto-pasta",
    title: "Pesto Pasta",
    description: "Pasta tossed with basil pesto and parmesan.",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e",
    ingredients: [
      { name: "Pasta", amount: "250", unit: "g" },
      { name: "Basil pesto", amount: "1/3", unit: "cup" },
      { name: "Parmesan cheese", amount: "1/4", unit: "cup" },
      { name: "Pine nuts", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Cook pasta until al dente.",
      "Toss with pesto and some pasta water.",
      "Top with parmesan and pine nuts.",
    ],
    cookTime: "20 min",
  },
  {
    id: "beef-burger",
    title: "Beef Burger",
    description: "Juicy homemade beef burger with toppings.",
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    ingredients: [
      { name: "Ground beef", amount: "200", unit: "g" },
      { name: "Burger bun", amount: "1" },
      { name: "Cheese slice", amount: "1" },
      { name: "Lettuce leaf", amount: "1" },
    ],
    steps: [
      "Form beef into a patty and season.",
      "Grill or pan-fry until cooked to preference.",
      "Assemble burger with cheese and toppings.",
    ],
    cookTime: "20 min",
  },
  {
    id: "pulled-pork-sandwich",
    title: "Pulled Pork Sandwich",
    description: "Slow-cooked pulled pork piled onto soft buns.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7a7a0",
    ingredients: [
      { name: "Pork shoulder", amount: "1", unit: "kg" },
      { name: "BBQ sauce", amount: "1", unit: "cup" },
      { name: "Burger buns", amount: "4" },
      { name: "Onion", amount: "1" },
    ],
    steps: [
      "Slow-cook pork with onions until tender.",
      "Shred pork and mix with BBQ sauce.",
      "Serve on buns.",
    ],
    cookTime: "6 hr",
  },
  {
    id: "burrito-bowl",
    title: "Burrito Bowl",
    description: "Deconstructed burrito with rice, beans, and toppings.",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591",
    ingredients: [
      { name: "Cooked rice", amount: "1", unit: "cup" },
      { name: "Black beans", amount: "1/2", unit: "cup" },
      { name: "Corn", amount: "1/4", unit: "cup" },
      { name: "Avocado", amount: "1/2" },
    ],
    steps: [
      "Place rice in a bowl.",
      "Top with beans, corn, and avocado.",
      "Add salsa or dressing as desired.",
    ],
    cookTime: "20 min",
  },
  {
    id: "chickpea-curry",
    title: "Chickpea Curry",
    description: "Vegan curry made with chickpeas and tomatoes.",
    imageUrl: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9a",
    ingredients: [
      { name: "Chickpeas", amount: "1", unit: "can" },
      { name: "Diced tomatoes", amount: "1", unit: "can" },
      { name: "Coconut milk", amount: "1", unit: "cup" },
      { name: "Curry powder", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Add tomatoes and chickpeas to a pan.",
      "Stir in curry powder and coconut milk.",
      "Simmer until thickened.",
    ],
    cookTime: "30 min",
  },
  {
    id: "thai-green-curry",
    title: "Thai Green Curry",
    description: "Fragrant curry with vegetables and coconut milk.",
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
    ingredients: [
      { name: "Green curry paste", amount: "2", unit: "tbsp" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Chicken or tofu", amount: "200", unit: "g" },
      { name: "Mixed vegetables", amount: "1", unit: "cup" },
    ],
    steps: [
      "Fry curry paste briefly.",
      "Add coconut milk and bring to a simmer.",
      "Add chicken or tofu and vegetables.",
      "Cook until everything is tender.",
    ],
    cookTime: "30 min",
  },
  {
    id: "gnocchi-tomato-sauce",
    title: "Gnocchi with Tomato Sauce",
    description: "Soft potato gnocchi tossed in tomato sauce.",
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e",
    ingredients: [
      { name: "Gnocchi", amount: "400", unit: "g" },
      { name: "Tomato sauce", amount: "2", unit: "cups" },
      { name: "Parmesan cheese", amount: "1/4", unit: "cup" },
      { name: "Basil leaves", amount: "4" },
    ],
    steps: [
      "Cook gnocchi until they float.",
      "Heat tomato sauce in a pan.",
      "Toss gnocchi with sauce and top with cheese and basil.",
    ],
    cookTime: "20 min",
  },
  {
    id: "egg-fried-rice",
    title: "Egg Fried Rice",
    description: "Stir-fried rice with egg and vegetables.",
    imageUrl: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56",
    ingredients: [
      { name: "Cooked rice", amount: "2", unit: "cups" },
      { name: "Eggs", amount: "2" },
      { name: "Frozen peas", amount: "1/2", unit: "cup" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Scramble eggs in a hot pan and remove.",
      "Stir-fry rice and peas.",
      "Add eggs back and season with soy sauce.",
    ],
    cookTime: "15 min",
  },
  {
    id: "teriyaki-chicken",
    title: "Teriyaki Chicken",
    description: "Chicken glazed with sweet teriyaki sauce.",
    imageUrl: "https://images.unsplash.com/photo-1608038509085-7bb9d5c0b93c",
    ingredients: [
      { name: "Chicken thighs", amount: "500", unit: "g" },
      { name: "Soy sauce", amount: "1/4", unit: "cup" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Garlic clove", amount: "1" },
    ],
    steps: [
      "Brown chicken in a pan.",
      "Add soy sauce, sugar, and garlic.",
      "Simmer until sauce thickens and coats chicken.",
    ],
    cookTime: "25 min",
  },
  {
    id: "greek-gyro",
    title: "Greek Gyro",
    description: "Seasoned meat wrapped in pita with tzatziki.",
    imageUrl: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56",
    ingredients: [
      { name: "Pita breads", amount: "2" },
      { name: "Cooked gyro meat or chicken", amount: "200", unit: "g" },
      { name: "Tomato slices", amount: "4" },
      { name: "Tzatziki sauce", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Warm pita breads.",
      "Fill with meat, tomato, and onions if desired.",
      "Top with tzatziki and wrap.",
    ],
    cookTime: "20 min",
  },
  {
    id: "prawn-coconut-curry",
    title: "Prawn Coconut Curry",
    description: "Creamy curry with prawns and coconut milk.",
    imageUrl: "https://images.unsplash.com/photo-1604908176997-1251884b08a2",
    ingredients: [
      { name: "Prawns", amount: "300", unit: "g" },
      { name: "Coconut milk", amount: "1", unit: "cup" },
      { name: "Onion", amount: "1/2" },
      { name: "Curry paste", amount: "2", unit: "tbsp" },
    ],
    steps: [
      "Sauté onion, then add curry paste.",
      "Stir in coconut milk.",
      "Add prawns and cook until pink.",
    ],
    cookTime: "25 min",
  },
  {
    id: "tuna-salad",
    title: "Tuna Salad",
    description: "Simple tuna salad with mayo and celery.",
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7a7a0",
    ingredients: [
      { name: "Canned tuna", amount: "1", unit: "can" },
      { name: "Mayonnaise", amount: "2", unit: "tbsp" },
      { name: "Celery stalk", amount: "1" },
      { name: "Lemon juice", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Drain tuna and place in a bowl.",
      "Mix with mayo, chopped celery, and lemon juice.",
      "Serve on bread or with crackers.",
    ],
    cookTime: "10 min",
  },
  {
    id: "overnight-oats",
    title: "Overnight Oats",
    description: "No-cook oats soaked in milk with fruit.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088",
    ingredients: [
      { name: "Rolled oats", amount: "1/2", unit: "cup" },
      { name: "Milk", amount: "1/2", unit: "cup" },
      { name: "Yogurt", amount: "1/4", unit: "cup" },
      { name: "Berries", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Combine oats, milk, and yogurt in a jar.",
      "Stir in berries.",
      "Refrigerate overnight.",
    ],
    cookTime: "8 hr",
  },
  {
    id: "chocolate-brownies",
    title: "Chocolate Brownies",
    description: "Fudgy chocolate brownies baked in a pan.",
    imageUrl: "https://images.unsplash.com/photo-1606312619349-37aa3b33d9ae",
    ingredients: [
      { name: "Butter", amount: "1/2", unit: "cup" },
      { name: "Sugar", amount: "1", unit: "cup" },
      { name: "Cocoa powder", amount: "1/3", unit: "cup" },
      { name: "Eggs", amount: "2" },
    ],
    steps: [
      "Melt butter and mix with sugar and cocoa.",
      "Beat in eggs and flour.",
      "Bake in a greased pan until set.",
    ],
    cookTime: "30 min",
  },
  {
    id: "banana-bread",
    title: "Banana Bread",
    description: "Moist banana loaf with a hint of cinnamon.",
    imageUrl: "https://images.unsplash.com/photo-1613478223719-2ab802602423",
    ingredients: [
      { name: "Ripe bananas", amount: "3" },
      { name: "Flour", amount: "2", unit: "cups" },
      { name: "Sugar", amount: "3/4", unit: "cup" },
      { name: "Eggs", amount: "2" },
    ],
    steps: [
      "Mash bananas and mix with sugar and eggs.",
      "Stir in flour and baking powder.",
      "Pour into a loaf pan and bake.",
    ],
    cookTime: "55 min",
  },
  {
    id: "apple-crumble",
    title: "Apple Crumble",
    description: "Baked apples topped with a buttery crumble.",
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    ingredients: [
      { name: "Apples", amount: "4" },
      { name: "Flour", amount: "1", unit: "cup" },
      { name: "Oats", amount: "1/2", unit: "cup" },
      { name: "Butter", amount: "1/2", unit: "cup" },
    ],
    steps: [
      "Slice apples and place in a baking dish.",
      "Mix flour, oats, sugar, and butter for the crumble.",
      "Sprinkle over apples and bake until golden.",
    ],
    cookTime: "45 min",
  },
  {
    id: "fruit-salad",
    title: "Fruit Salad",
    description: "Mixed fresh fruits tossed with citrus.",
    imageUrl: "https://images.unsplash.com/photo-1543353071-873f17a7a088",
    ingredients: [
      { name: "Strawberries", amount: "1", unit: "cup" },
      { name: "Grapes", amount: "1", unit: "cup" },
      { name: "Pineapple chunks", amount: "1", unit: "cup" },
      { name: "Orange juice", amount: "1/4", unit: "cup" },
    ],
    steps: [
      "Combine chopped fruits in a bowl.",
      "Pour over orange juice and toss.",
      "Chill before serving.",
    ],
    cookTime: "15 min",
  },
];

async function seed() {
  const colRef = collection(db, "publicRecipes");

  for (const recipe of publicRecipes) {
    const data = {
      ...recipe,
      imageUrl:
        recipe.imageUrl ||
        "https://via.placeholder.com/600x400?text=No+Image+Available",
    };
    await setDoc(doc(colRef, recipe.id), data, { merge: true });
    console.log(`✅ Synced (created or updated): ${recipe.title}`);
  }

  console.log("All recipes synced or added successfully!");
}

seed().catch(console.error);
